-- DATABASE CREATION SECTION 
USE master
IF EXISTS (SELECT* FROM sys.databases WHERE name = 'MMSDB')
DROP DATABASE MMSDB 
CREATE DATABASE MMSDB
USE MMSDB


-- TABLE CREATION SECTION
CREATE TABLE [user] (
UserID INT IDENTITY (1,1) PRIMARY KEY NOT NULL , 
Username VARCHAR(20) UNIQUE NOT NULL, 
[Password] VARCHAR(12) NOT NULL, 
ProfilePicture VARCHAR(MAX)
);

CREATE TABLE Song (
SongID INT IDENTITY (1,1) PRIMARY KEY NOT NULL, 
Title VARCHAR (MAX) NOT NULL, 
Genre VARCHAR (MAX) NOT NULL,
[Length] INT NOT NULL, 
);

CREATE TABLE Playlist (
PlaylistID INT IDENTITY (1,1) PRIMARY KEY NOT NULL, 
UserID INT FOREIGN KEY REFERENCES [User] (UserID), 
SongID INT FOREIGN KEY REFERENCES Song (SongID), 
PlaylistName VARCHAR (10) NOT NULL,
);


-- TABLE ALTERATION SECTION 
-- TABLEINSERTION SECTION 

INSERT INTO [user] (Username, [Password], ProfilePicture) 
VALUES ('Ankonisaho Madima', 'anko_m2005', 'https://cdn.shopify.com/s/files/1/0051/6295/8946/products/barbiedreamhousepink_wetpaint_hero.jpg?v=1661784289') 

-- TABLE MANIPULATION SECTION
SELECT*FROM [user];
SELECT*FROM Song;
SELECT *FROM Playlist;
-- STORED PROCEDURS SECTION 